project:
  type: website

website:
  title: "Ricky Woznichak"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    background: "#050404"
    left:
      - text: Home
        file: index.qmd
      - text: Marketing Analytics
        file: FinalDashboard.qmd
      - text: My Best Friend
        file: JimmyPics.qmd
   
       
      
format:
  html:
    theme: sketchy
    backgroundcolor: "#050404"
    fontcolor: "#fdfcfb"
    linkcolor: "#e5f731"
    mainfont: "monospace"
    fontsize: 18px
    
